apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restaurant-api-ingress
  annotations: {kubernetes.io/ingress.class: alb, alb.ingress.kubernetes.io/scheme: internet-facing}
spec:
  rules: [{http: {paths: [{path: /, pathType: Prefix, backend: {service: {name: restaurant-api, port: {number: 80}}}}]}}]
